#!/usr/bin/env python3
"""
Brand-Agnostic Carousel Renderer — v3 (Editorial Dark/Light Theme System)

All brand-specific values (colors, fonts, localized strings) are loaded from
`theme.json`. To rebrand, edit theme.json — do not edit this file.

Theme lookup order:
  1. <carousel_dir>/theme.json     (per-carousel override)
  2. <carousel_dir>/../theme.json  (project-level theme)
  3. <script_dir>/theme.json       (default theme)
  4. Built-in fallback             (used if no file found)

Per-slide theme switching:
  - "theme": "dark"  → Dark bg, light text, accent highlights
  - "theme": "light" → Light bg, dark text, accent highlights
  - If "theme" missing: hook/cta default to dark, body defaults to light.
"""
import json, sys
from pathlib import Path
from PIL import Image, ImageDraw, ImageFont, ImageFilter

# ── Canvas ────────────────────────────────────────────────────────────────────
W, H    = 1080, 1350          # Instagram 4:5 portrait
PAD     = 96
TOP_H   = 80
BOT_H   = 80
C_TOP   = TOP_H + 28
C_BOT   = H - BOT_H - 24
C_W     = W - PAD * 2
C_H     = C_BOT - C_TOP
CR      = 20                  # card corner radius
CPX     = 40                  # card padding x
CPY     = 32                  # card padding y

# ── Built-in fallback theme (used only if no theme.json found) ────────────────
DEFAULT_THEME = {
    "fonts": {
        "dirs": {"brand_fonts": "assets/fonts", "system_mono": "C:/Windows/Fonts"},
        "latin": {
            "display_bold":     ["LexendDeca-Bold.ttf"],
            "display_semibold": ["LexendDeca-SemiBold.ttf"],
            "display_medium":   ["LexendDeca-Medium.ttf"],
            "body_regular":     ["Inter-Regular.ttf"],
            "body_medium":      ["Inter-Medium.ttf"],
            "body_semibold":    ["Inter-SemiBold.ttf"],
        },
        "cjk": {
            "heavy":   ["ChillDuanSans_Heavy.otf"],
            "medium":  ["ChillDuanSans_Medium.otf"],
            "regular": ["ChillDuanSans_Regular.otf"],
            "light":   ["ChillDuanSans_Light.otf"],
        },
        "mono": {"regular": ["consola.ttf"], "bold": ["consolab.ttf"]},
    },
    "i18n": {
        "en": {"swipe": "SWIPE →",  "follow_footer": "FOLLOW FOR MORE"},
        "zh": {"swipe": "左滑 →",   "follow_footer": "記得 FOLLOW"},
    },
    "code_block": {
        "bg": "#0D1117", "keyword": "#C4B5FD", "text": "#CBD5E1",
        "traffic": ["#FF5F57", "#FFBD2E", "#28C940"],
    },
    "cta_button_gradient": ["#A78BFA", "#C4B5FD"],
    "cta_glow_color":      "#A78BFA",
    "themes": {
        "dark": {
            "bg": "#111827", "headline": "#FFFFFF", "body": "#E0E7FF",
            "label": "#C4B5FD", "divider": "#C4B5FD", "muted": "#8A8E9C",
            "hairline": "#FFFFFF", "hairline_a": 38,
            "accent_hi_bg": "#A78BFA", "accent_hi_fg": "#111827",
            "pill_bg": "#1F2937", "pill_border": "#A78BFA", "pill_border_a": 90,
            "pill_fg": "#FFFFFF", "pill_active_bg": "#A78BFA", "pill_active_fg": "#111827",
            "card_bg": "#A78BFA", "card_bg_a": 30, "card_border": "#A78BFA",
            "card_label": "#C4B5FD", "card_text": "#FFFFFF",
            "cmp_old_bg": "#FF899F", "cmp_old_bg_a": 48, "cmp_old_label": "#FF899F",
            "cmp_new_bg": "#C4B5FD", "cmp_new_bg_a": 38, "cmp_new_label": "#C4B5FD",
            "img_border": "#FFFFFF", "img_border_a": 51,
        },
        "light": {
            "bg": "#FAFAFA", "headline": "#111827", "body": "#374151",
            "label": "#7C3AED", "divider": "#8B5CF6", "muted": "#6B7280",
            "hairline": "#111827", "hairline_a": 26,
            "accent_hi_bg": "#A78BFA", "accent_hi_fg": "#111827",
            "pill_bg": "#FFFFFF", "pill_border": "#111827", "pill_border_a": 255,
            "pill_fg": "#111827", "pill_active_bg": "#A78BFA", "pill_active_fg": "#111827",
            "card_bg": "#111827", "card_bg_a": 255, "card_border": None,
            "card_label": "#C4B5FD", "card_text": "#FFFFFF",
            "cmp_old_bg": "#FAE8E8", "cmp_old_bg_a": 255, "cmp_old_label": "#FF899F",
            "cmp_new_bg": "#EDE9FE", "cmp_new_bg_a": 255, "cmp_new_label": "#7C3AED",
            "img_border": "#111827", "img_border_a": 26,
        },
    },
}

# ── Theme loader ──────────────────────────────────────────────────────────────
def _deep_merge(base, override):
    """Recursively merge `override` into `base` (override wins)."""
    out = dict(base)
    for k, v in override.items():
        if k in out and isinstance(out[k], dict) and isinstance(v, dict):
            out[k] = _deep_merge(out[k], v)
        else:
            out[k] = v
    return out

def load_theme(carousel_dir: Path) -> dict:
    """Look for theme.json in carousel_dir, parent, then script dir."""
    script_dir = Path(__file__).parent
    candidates = [
        carousel_dir / "theme.json",
        carousel_dir.parent / "theme.json",
        script_dir / "theme.json",
    ]
    for p in candidates:
        if p.exists():
            print(f"Theme: {p}")
            user_theme = json.loads(p.read_text(encoding="utf-8"))
            return _deep_merge(DEFAULT_THEME, user_theme)
    print("Theme: built-in fallback")
    return DEFAULT_THEME

# ── Fonts ─────────────────────────────────────────────────────────────────────
def _resolve_font(filenames, font_dir, fallback_dir=None):
    """Return first existing font path from a list of candidate filenames."""
    for fname in filenames:
        p = Path(font_dir) / fname
        if p.exists():
            return str(p)
        if fallback_dir:
            p = Path(fallback_dir) / fname
            if p.exists():
                return str(p)
    # last-resort: return the first candidate (will raise nicer error at use site)
    return str(Path(font_dir) / filenames[0])

def _f(path, size):
    return ImageFont.truetype(path, size)

def load_fonts(theme: dict, lang: str = "en"):
    """Build a font dict keyed by role, based on theme config + language."""
    fcfg = theme["fonts"]
    script_dir = Path(__file__).parent
    brand_dir = script_dir / fcfg["dirs"]["brand_fonts"]
    mono_dir  = Path(fcfg["dirs"]["system_mono"])

    # Resolve all font paths with fallbacks
    L = fcfg["latin"]; CJ = fcfg["cjk"]; M = fcfg["mono"]
    cjk_heavy  = _resolve_font(CJ["heavy"],   brand_dir)
    cjk_med    = _resolve_font(CJ["medium"],  brand_dir)
    cjk_reg    = _resolve_font(CJ["regular"], brand_dir)
    cjk_light  = _resolve_font(CJ["light"],   brand_dir)

    # Latin fonts fall back to CJK heavy/medium/regular if missing
    disp_b  = _resolve_font(L["display_bold"]     + CJ["heavy"],   brand_dir)
    disp_sb = _resolve_font(L["display_semibold"] + CJ["heavy"],   brand_dir)
    disp_m  = _resolve_font(L["display_medium"]   + CJ["medium"],  brand_dir)
    body_r  = _resolve_font(L["body_regular"]     + CJ["regular"], brand_dir)
    body_m  = _resolve_font(L["body_medium"]      + CJ["medium"],  brand_dir)
    body_sb = _resolve_font(L["body_semibold"]    + CJ["heavy"],   brand_dir)

    mono_r  = _resolve_font(M["regular"], mono_dir, brand_dir)
    mono_b  = _resolve_font(M["bold"],    mono_dir, brand_dir)

    # CJK languages get the CJK font stack for headlines/body
    cjk_langs = {"zh", "ja", "ko"}
    if lang in cjk_langs:
        return {
            "topbar":      _f(cjk_heavy, 26),
            "counter":     _f(body_m,    26),
            "label":       _f(cjk_heavy, 26),
            "headline_xl": _f(cjk_heavy, 88),
            "headline_lg": _f(cjk_heavy, 72),
            "headline_md": _f(cjk_heavy, 58),
            "headline_sm": _f(cjk_heavy, 48),
            "body_lg":     _f(cjk_med,   40),
            "body":        _f(cjk_reg,   36),
            "body_sm":     _f(cjk_reg,   30),
            "body_bold":   _f(cjk_heavy, 36),
            "card_label":  _f(cjk_heavy, 24),
            "card_body":   _f(cjk_reg,   34),
            "code":        _f(mono_r,    30),
            "code_kw":     _f(mono_b,    30),
            "caption":     _f(cjk_light, 24),
            "pill":        _f(cjk_med,   27),
        }
    # Latin scripts (en, es, fr, de, etc.)
    return {
        "topbar":      _f(disp_m,  26),
        "counter":     _f(body_m,  26),
        "label":       _f(disp_m,  26),
        "headline_xl": _f(disp_b,  96),
        "headline_lg": _f(disp_b,  76),
        "headline_md": _f(disp_b,  58),
        "headline_sm": _f(disp_sb, 46),
        "body_lg":     _f(body_r,  38),
        "body":        _f(body_r,  34),
        "body_sm":     _f(body_r,  28),
        "body_bold":   _f(body_sb, 34),
        "card_label":  _f(disp_m,  22),
        "card_body":   _f(body_r,  32),
        "code":        _f(mono_r,  28),
        "code_kw":     _f(mono_b,  28),
        "caption":     _f(body_m,  24),
        "pill":        _f(body_m,  26),
    }

# ── Theme accessor ────────────────────────────────────────────────────────────
def get_palette(slide: dict, theme: dict) -> dict:
    """Return the palette for a slide based on its 'theme' field."""
    themes = theme["themes"]
    name = slide.get("theme")
    if name and name in themes:
        return themes[name]
    if slide.get("type") in ("hook", "cta"):
        return themes["dark"]
    return themes["light"]

def i18n(theme: dict, lang: str, key: str, default: str = "") -> str:
    return theme.get("i18n", {}).get(lang, {}).get(key, default)

# ── Color helpers ─────────────────────────────────────────────────────────────
def rgb(hex_c):
    h = hex_c.lstrip("#")
    return tuple(int(h[i:i+2], 16) for i in (0, 2, 4))

def rgba(hex_c, a=255):
    return rgb(hex_c) + (a,)

# ── Text helpers ──────────────────────────────────────────────────────────────
def wrap(text, font, max_w, draw):
    lines = []
    for para in text.split("\n"):
        words = para.split()
        if not words:
            lines.append(""); continue
        cur = []
        for w in words:
            test = " ".join(cur + [w])
            if draw.textbbox((0, 0), test, font=font)[2] <= max_w:
                cur.append(w)
            else:
                if cur: lines.append(" ".join(cur))
                cur = [w]
        if cur: lines.append(" ".join(cur))
    return lines

def lh(font, draw, sp=1.45):
    bb = draw.textbbox((0, 0), "Ag", font=font)
    return int((bb[3] - bb[1]) * sp)

def th(text, font, max_w, draw, sp=1.45):
    return lh(font, draw, sp) * len(wrap(text, font, max_w, draw))

def draw_plain(draw, text, xy, font, color, max_w, sp=1.45, align="left"):
    x, y = xy
    lines = wrap(text, font, max_w, draw)
    lhv = lh(font, draw, sp)
    for ln in lines:
        if align == "center":
            lw = draw.textbbox((0, 0), ln, font=font)[2]
            draw.text((x + (max_w - lw) // 2, y), ln, font=font, fill=rgb(color))
        else:
            draw.text((x, y), ln, font=font, fill=rgb(color))
        y += lhv
    return y

def draw_rich(draw, text, xy, font, def_c, acc_c, max_w,
              sp=1.3, acc_bg=None, acc_fg=None):
    """Draw text with *accent* words. Filled pill behind word if acc_bg set."""
    x, y = xy
    parts = text.split("*")
    words = []
    for i, p in enumerate(parts):
        for w in p.split():
            words.append((w, i % 2 == 1))

    lines, cur = [], []
    for word, acc in words:
        test = " ".join(w for w, _ in cur) + (" " if cur else "") + word
        if draw.textbbox((0, 0), test, font=font)[2] <= max_w:
            cur.append((word, acc))
        else:
            if cur: lines.append(cur)
            cur = [(word, acc)]
    if cur: lines.append(cur)

    lhv = lh(font, draw, sp)
    for ln in lines:
        dx = x
        for word, acc in ln:
            wbb = draw.textbbox((dx, y), word, font=font)
            if acc:
                if acc_bg:
                    pad_x, pad_y = 6, 3
                    draw.rounded_rectangle(
                        [(wbb[0] - pad_x, wbb[1] - pad_y),
                         (wbb[2] + pad_x, wbb[3] + pad_y)],
                        radius=8, fill=rgb(acc_bg))
                    fg = acc_fg if acc_fg else def_c
                    draw.text((dx, y), word, font=font, fill=rgb(fg))
                else:
                    draw.text((dx, y), word, font=font, fill=rgb(acc_c))
            else:
                draw.text((dx, y), word, font=font, fill=rgb(def_c))
            dx += draw.textbbox((0, 0), word + " ", font=font)[2]
        y += lhv
    return y

# ── Chrome (top/bottom bars) ──────────────────────────────────────────────────
def _hairline(draw, p, x1, y, x2):
    """Thin horizontal separator using palette hairline color + alpha."""
    base = rgb(p["bg"])
    hc   = rgb(p["hairline"])
    a    = p["hairline_a"] / 255
    blend = tuple(int(base[i] * (1 - a) + hc[i] * a) for i in range(3))
    draw.line([(x1, y), (x2, y)], fill=blend, width=1)

def draw_top_bar(draw, fonts, palette, brand, num, total):
    p = palette
    brand_str   = brand.upper()
    counter_str = f"{num:02d} / {total:02d}"
    draw.text((PAD, 26), brand_str, font=fonts["topbar"], fill=rgb(p["headline"]))
    cw = draw.textbbox((0, 0), counter_str, font=fonts["counter"])[2]
    draw.text((W - PAD - cw, 26), counter_str,
              font=fonts["counter"], fill=rgb(p["muted"]))
    _hairline(draw, p, PAD, TOP_H + 4, W - PAD)

def draw_bot_bar(draw, fonts, palette, num, total, lang, theme):
    p     = palette
    swipe = i18n(theme, lang, "swipe", "SWIPE →")
    page  = f"{num:02d} / {total:02d}"
    by    = H - BOT_H
    _hairline(draw, p, PAD, by - 4, W - PAD)
    draw.text((PAD, by + 26), swipe, font=fonts["caption"], fill=rgb(p["label"]))
    pw = draw.textbbox((0, 0), page, font=fonts["caption"])[2]
    draw.text((W - PAD - pw, by + 26), page,
              font=fonts["caption"], fill=rgb(p["muted"]))

def draw_label(draw, fonts, palette, text, y):
    """Small-caps category label with accent dot trio beneath."""
    p = palette
    draw.text((PAD, y), text.upper(), font=fonts["label"], fill=rgb(p["label"]))
    bb = draw.textbbox((PAD, y), text.upper(), font=fonts["label"])
    dot_y = bb[3] + 14
    for i in range(3):
        cx = PAD + i * 18
        draw.ellipse([(cx, dot_y), (cx + 7, dot_y + 7)], fill=rgb(p["label"]))
    return dot_y + 7 + 14

def draw_divider(draw, palette, y):
    """Solid accent bar — 80×6, not a thin line."""
    p = palette
    draw.rounded_rectangle([(PAD, y + 8), (PAD + 80, y + 14)],
                           radius=3, fill=rgb(p["divider"]))
    return y + 32

def base_slide(palette):
    return Image.new("RGB", (W, H), rgb(palette["bg"]))

# ── Content blocks ────────────────────────────────────────────────────────────
def block_callout_card(img, draw, fonts, palette, x, y, w, text, label=None):
    p   = palette
    tmp = ImageDraw.Draw(img)
    lbl_h = 0
    if label:
        bb = tmp.textbbox((0, 0), label.upper(), font=fonts["card_label"])
        lbl_h = (bb[3] - bb[1]) + 16
    body_h = th(text, fonts["card_body"], w - CPX * 2, tmp, 1.5)
    total  = lbl_h + body_h + CPY * 2

    if p["card_bg_a"] < 255:
        overlay = Image.new("RGBA", (w, total), (0, 0, 0, 0))
        ImageDraw.Draw(overlay).rounded_rectangle(
            [(0, 0), (w, total)], radius=CR,
            fill=rgba(p["card_bg"], p["card_bg_a"]))
        img.paste(overlay, (x, y), overlay)
    else:
        draw.rounded_rectangle([(x, y), (x + w, y + total)],
                               radius=CR, fill=rgb(p["card_bg"]))
    if p["card_border"]:
        draw.rounded_rectangle([(x, y), (x + w, y + total)],
                               radius=CR, outline=rgb(p["card_border"]), width=2)

    cy = y + CPY
    if label:
        draw.text((x + CPX, cy), label.upper(),
                  font=fonts["card_label"], fill=rgb(p["card_label"]))
        bb = draw.textbbox((0, 0), label.upper(), font=fonts["card_label"])
        cy += (bb[3] - bb[1]) + 16
    draw_plain(draw, text, (x + CPX, cy), fonts["card_body"],
               p["card_text"], w - CPX * 2, sp=1.5)
    return y + total

def block_comparison_card(img, draw, fonts, palette, x, y, w, text,
                          label, label_c, bg_c, bg_a, side_c):
    p   = palette
    tmp = ImageDraw.Draw(img)
    bb  = tmp.textbbox((0, 0), label.upper(), font=fonts["card_label"])
    lbl_h = (bb[3] - bb[1]) + 16
    body_h = th(text, fonts["card_body"], w - CPX * 2, tmp, 1.5)
    total  = lbl_h + body_h + CPY * 2

    if bg_a < 255:
        overlay = Image.new("RGBA", (w, total), (0, 0, 0, 0))
        ImageDraw.Draw(overlay).rounded_rectangle(
            [(0, 0), (w, total)], radius=CR, fill=rgba(bg_c, bg_a))
        img.paste(overlay, (x, y), overlay)
    else:
        draw.rounded_rectangle([(x, y), (x + w, y + total)],
                               radius=CR, fill=rgb(bg_c))
    draw.rounded_rectangle([(x, y + 12), (x + 5, y + total - 12)],
                           radius=3, fill=rgb(side_c))

    cy = y + CPY
    draw.text((x + CPX, cy), label.upper(),
              font=fonts["card_label"], fill=rgb(label_c))
    cy += lbl_h
    draw_plain(draw, text, (x + CPX, cy), fonts["card_body"],
               p["body"], w - CPX * 2, sp=1.5)
    return y + total

def block_code(img, draw, fonts, theme, x, y, w, lines):
    """macOS-style code block — uses theme.code_block colors."""
    cb = theme["code_block"]
    tmp = ImageDraw.Draw(img)
    lhv   = lh(fonts["code"], tmp, 1.7)
    hdr_h = 52
    body_h = len(lines) * lhv + CPY
    total = hdr_h + body_h + CPY

    draw.rounded_rectangle([(x, y), (x + w, y + total)],
                           radius=CR, fill=rgb(cb["bg"]))
    dy = y + hdr_h // 2 - 6
    for di, dc in enumerate(cb["traffic"]):
        draw.ellipse([(x + CPX + di * 22, dy),
                      (x + CPX + di * 22 + 12, dy + 12)], fill=rgb(dc))
    cy = y + hdr_h + CPY // 2
    for (kw, rest) in lines:
        kw_w = draw.textbbox((0, 0), kw + "  ", font=fonts["code_kw"])[2]
        draw.text((x + CPX, cy), kw, font=fonts["code_kw"], fill=rgb(cb["keyword"]))
        draw.text((x + CPX + kw_w, cy), rest,
                  font=fonts["code"], fill=rgb(cb["text"]))
        cy += lhv
    return y + total

def block_pills(img, draw, fonts, palette, x, y, tags, active_idx=None):
    p = palette
    ph, ppx, gap = 56, 32, 14
    px, row_y = x, y
    for i, tag in enumerate(tags):
        tw = draw.textbbox((0, 0), tag, font=fonts["pill"])[2]
        pw = tw + ppx * 2
        if px + pw > W - PAD:
            px = x; row_y += ph + 12
        is_act = (active_idx is not None and i == active_idx)
        if is_act:
            draw.rounded_rectangle([(px, row_y), (px + pw, row_y + ph)],
                                   radius=ph // 2, fill=rgb(p["pill_active_bg"]))
            fg = p["pill_active_fg"]
        else:
            draw.rounded_rectangle([(px, row_y), (px + pw, row_y + ph)],
                                   radius=ph // 2, fill=rgb(p["pill_bg"]))
            border_col = rgb(p["pill_border"])
            if p["pill_border_a"] < 255:
                bgc = rgb(p["pill_bg"])
                a = p["pill_border_a"] / 255
                border_col = tuple(int(bgc[j] * (1-a) + border_col[j] * a)
                                   for j in range(3))
            draw.rounded_rectangle([(px, row_y), (px + pw, row_y + ph)],
                                   radius=ph // 2, outline=border_col, width=2)
            fg = p["pill_fg"]
        tb = draw.textbbox((0, 0), tag, font=fonts["pill"])
        t_h = tb[3] - tb[1]
        draw.text((px + ppx, row_y + (ph - t_h) // 2 - tb[1]),
                  tag, font=fonts["pill"], fill=rgb(fg))
        px += pw + gap
    return row_y + ph + 10

def block_bullets(draw, fonts, palette, x, y, bullets, max_w):
    p = palette
    for bullet in bullets:
        dot_y = y + 16
        draw.ellipse([(x, dot_y), (x + 11, dot_y + 11)], fill=rgb(p["divider"]))
        ey = draw_rich(draw, bullet, (x + 32, y), fonts["body"],
                       p["body"], p["divider"], max_w - 32, sp=1.45,
                       acc_bg=p["accent_hi_bg"], acc_fg=p["accent_hi_fg"])
        y = ey + 18
    return y

def block_hero_image(img, draw, palette, image_path, x, y, max_w, max_h):
    p = palette
    try:
        ref = Image.open(str(image_path)).convert("RGBA")
        ratio = max_w / ref.width
        nw = max_w
        nh = min(int(ref.height * ratio), max_h)
        ref = ref.resize((nw, int(ref.height * ratio)), Image.LANCZOS)
        if ref.height > nh:
            top = (ref.height - nh) // 2
            ref = ref.crop((0, top, nw, top + nh))
        mask = Image.new("L", (nw, nh), 0)
        ImageDraw.Draw(mask).rounded_rectangle([(0, 0), (nw, nh)],
                                                radius=CR, fill=255)
        out = Image.new("RGBA", (nw, nh), (0, 0, 0, 0))
        out.paste(ref, (0, 0), mask)
        overlay = Image.new("RGBA", (nw, nh), (0, 0, 0, 0))
        od = ImageDraw.Draw(overlay)
        bg_rgb = rgb(p["bg"])
        for row in range(int(nh * 0.6), nh):
            t_ = (row - nh * 0.6) / (nh * 0.4)
            a = int(180 * t_)
            od.line([(0, row), (nw, row)], fill=bg_rgb + (a,))
        out = Image.alpha_composite(out, overlay)
        img.paste(out.convert("RGB"), (x, y), out)
        border = Image.new("RGBA", (nw, nh), (0, 0, 0, 0))
        ImageDraw.Draw(border).rounded_rectangle(
            [(0, 0), (nw, nh)], radius=CR,
            outline=rgba(p["img_border"], p["img_border_a"]), width=2)
        img.paste(border, (x, y), border)
        return y + nh + 20
    except Exception as e:
        print(f"  Hero image error: {e}")
        return y

def block_image(img, draw, palette, image_path, x, y, max_w, max_h):
    p = palette
    try:
        ref = Image.open(str(image_path)).convert("RGBA")
        scale = min(max_w / ref.width, max_h / ref.height)
        nw, nh = int(ref.width * scale), int(ref.height * scale)
        ref = ref.resize((nw, nh), Image.LANCZOS)
        ox = x + (max_w - nw) // 2
        mask = Image.new("L", (nw, nh), 0)
        ImageDraw.Draw(mask).rounded_rectangle([(0, 0), (nw, nh)], radius=CR, fill=255)
        out = Image.new("RGBA", (nw, nh), (0, 0, 0, 0))
        out.paste(ref, (0, 0), mask)
        img.paste(out.convert("RGB"), (ox, y), out)
        border = Image.new("RGBA", (nw, nh), (0, 0, 0, 0))
        ImageDraw.Draw(border).rounded_rectangle(
            [(0, 0), (nw, nh)], radius=CR,
            outline=rgba(p["img_border"], p["img_border_a"]), width=2)
        img.paste(border, (ox, y), border)
        return y + nh + 20
    except Exception as e:
        print(f"  Image error: {e}")
        return y

def block_logo_row(img, draw, palette, image_paths, x, y, max_w, box_size=140):
    p = palette
    n = len(image_paths)
    if n == 0: return y
    gap = 24
    total_w = n * box_size + (n - 1) * gap
    start_x = x + (max_w - total_w) // 2
    for i, ip in enumerate(image_paths):
        bx = start_x + i * (box_size + gap)
        draw.rounded_rectangle([(bx, y), (bx + box_size, y + box_size)],
                               radius=18, fill=rgb("#FFFFFF"))
        try:
            logo = Image.open(str(ip)).convert("RGBA")
            pad = 20
            inner = box_size - pad * 2
            ratio = min(inner / logo.width, inner / logo.height)
            lw, lh_ = int(logo.width * ratio), int(logo.height * ratio)
            logo = logo.resize((lw, lh_), Image.LANCZOS)
            lx = bx + (box_size - lw) // 2
            ly = y + (box_size - lh_) // 2
            img.paste(logo, (lx, ly), logo)
        except Exception as e:
            print(f"  Logo error {ip}: {e}")
    return y + box_size + 20

def block_split_images(img, draw, palette, left_path, right_path,
                       x, y, max_w, max_h=420, labels=None):
    p = palette
    gap = 16
    each_w = (max_w - gap) // 2
    for i, ip in enumerate([left_path, right_path]):
        bx = x + i * (each_w + gap)
        try:
            ref = Image.open(str(ip)).convert("RGBA")
            ratio = min(each_w / ref.width, max_h / ref.height)
            nw, nh = int(ref.width * ratio), int(ref.height * ratio)
            ref = ref.resize((nw, nh), Image.LANCZOS)
            mask = Image.new("L", (nw, nh), 0)
            ImageDraw.Draw(mask).rounded_rectangle(
                [(0, 0), (nw, nh)], radius=CR, fill=255)
            out = Image.new("RGBA", (nw, nh), (0, 0, 0, 0))
            out.paste(ref, (0, 0), mask)
            px_ = bx + (each_w - nw) // 2
            img.paste(out.convert("RGB"), (px_, y), out)
            if labels and i < len(labels):
                draw.text((px_, y + nh + 8), labels[i].upper(),
                          fill=rgb(p["label"]))
        except Exception as e:
            print(f"  Split image error: {e}")
    return y + max_h + 40

# ── Slide renderers ───────────────────────────────────────────────────────────
def render_hook(config, slide, fonts, theme, cdir):
    p    = get_palette(slide, theme)
    img  = base_slide(p)
    draw = ImageDraw.Draw(img)
    lang = config.get("language", "en")
    n, t = slide["number"], config["total_slides"]
    brand = config["profile"]["display_name"]

    draw_top_bar(draw, fonts, p, brand, n, t)
    draw_bot_bar(draw, fonts, p, n, t, lang, theme)

    y = C_TOP + 16
    if slide.get("label"):
        y = draw_label(draw, fonts, p, slide["label"], y) + 6

    hook  = slide["text"].rstrip(".")
    clean = hook.replace("*", "")
    hfont = fonts["headline_xl"] if len(clean) < 50 else fonts["headline_lg"]
    y = draw_rich(draw, hook, (PAD, y), hfont,
                  p["headline"], p["divider"], C_W, sp=1.12,
                  acc_bg=p["accent_hi_bg"], acc_fg=p["accent_hi_fg"])
    y = draw_divider(draw, p, y)

    if slide.get("subtitle"):
        y = draw_plain(draw, slide["subtitle"], (PAD, y + 8),
                       fonts["body_lg"], p["body"], C_W, sp=1.5) + 20

    if slide.get("pills"):
        y += 12
        y = block_pills(img, draw, fonts, p, PAD, y,
                        slide["pills"], slide.get("pills_active"))
    elif slide.get("image"):
        ip = cdir / "reference" / slide["image"]
        if ip.exists():
            y += 12
            layout = slide.get("image_layout", "inline")
            if layout == "hero":
                block_hero_image(img, draw, p, ip, PAD, y, C_W, max_h=480)
            else:
                block_image(img, draw, p, ip, PAD, y, C_W, max_h=380)
    return img

def render_body(config, slide, fonts, theme, cdir):
    p    = get_palette(slide, theme)
    img  = base_slide(p)
    draw = ImageDraw.Draw(img)
    lang = config.get("language", "en")
    n, t = slide["number"], config["total_slides"]
    brand = config["profile"]["display_name"]

    draw_top_bar(draw, fonts, p, brand, n, t)
    draw_bot_bar(draw, fonts, p, n, t, lang, theme)

    tmp = ImageDraw.Draw(img)
    est = 0
    if slide.get("label"):   est += 54
    if slide.get("title"):
        clean = slide["title"].replace("*", "")
        tfont = fonts["headline_xl"] if len(clean) < 35 else fonts["headline_lg"]
        est += th(clean, tfont, C_W, tmp, 1.12) + 32 + 20
    if slide.get("text"):
        txf = fonts["body_lg"] if not slide.get("title") else fonts["body"]
        est += th(slide["text"].replace("*", ""), txf, C_W, tmp, 1.55) + 18
    if slide.get("bullets"):
        for b in slide["bullets"]:
            est += th(b.replace("*", ""), fonts["body"], C_W - 32, tmp, 1.45) + 18
    if slide.get("comparison"):
        for k in ("old", "new"):
            cmp_ = slide["comparison"].get(k)
            if cmp_:
                est += th(cmp_["text"], fonts["card_body"],
                          C_W - CPX * 2, tmp, 1.5) + CPY * 2 + 44 + 16
    if slide.get("card"):
        est += th(slide["card"]["text"], fonts["card_body"],
                  C_W - CPX * 2, tmp, 1.5) + CPY * 2 + 44 + 28
    if slide.get("code_block"):
        est += 52 + len(slide["code_block"]) * lh(fonts["code"], tmp, 1.7) + CPY*2 + 28
    if slide.get("pills"):
        est += 66

    avail = C_H
    y = C_TOP + (max(16, (avail - est) // 3) if est < avail * 0.62 else 16)

    if slide.get("label"):
        y = draw_label(draw, fonts, p, slide["label"], y) + 4

    if slide.get("title"):
        title_draw = slide["title"].rstrip(".")
        if "*" not in title_draw:
            parts = title_draw.rsplit(" ", 1)
            if len(parts) == 2:
                title_draw = parts[0] + " *" + parts[1] + "*"
        tclean = title_draw.replace("*", "")
        tfont  = fonts["headline_xl"] if len(tclean) < 35 else fonts["headline_lg"]
        y = draw_rich(draw, title_draw, (PAD, y), tfont,
                      p["headline"], p["divider"], C_W, sp=1.12,
                      acc_bg=p["accent_hi_bg"], acc_fg=p["accent_hi_fg"])
        y = draw_divider(draw, p, y)

    if slide.get("text"):
        has_title = bool(slide.get("title"))
        txfont = fonts["body_lg"] if not has_title else fonts["body"]
        y = draw_rich(draw, slide["text"], (PAD, y + 4), txfont,
                      p["body"], p["divider"], C_W, sp=1.55,
                      acc_bg=p["accent_hi_bg"], acc_fg=p["accent_hi_fg"]) + 18

    if slide.get("bullets"):
        y = block_bullets(draw, fonts, p, PAD, y, slide["bullets"], C_W)

    if slide.get("comparison"):
        comp = slide["comparison"]
        y += 12
        if comp.get("old"):
            o = comp["old"]
            y = block_comparison_card(img, draw, fonts, p, PAD, y, C_W,
                                      o["text"],
                                      label=o.get("label", "OLD WAY"),
                                      label_c=p["cmp_old_label"],
                                      bg_c=p["cmp_old_bg"],
                                      bg_a=p["cmp_old_bg_a"],
                                      side_c=p["cmp_old_label"]) + 18
        if comp.get("new"):
            nw_ = comp["new"]
            y = block_comparison_card(img, draw, fonts, p, PAD, y, C_W,
                                      nw_["text"],
                                      label=nw_.get("label", "NEW WAY"),
                                      label_c=p["cmp_new_label"],
                                      bg_c=p["cmp_new_bg"],
                                      bg_a=p["cmp_new_bg_a"],
                                      side_c=p["cmp_new_label"]) + 18

    if slide.get("card"):
        cd = slide["card"]
        y += 8
        y = block_callout_card(img, draw, fonts, p, PAD, y, C_W,
                               cd["text"], label=cd.get("label")) + 22

    if slide.get("code_block"):
        y += 8
        y = block_code(img, draw, fonts, theme, PAD, y, C_W, slide["code_block"]) + 22

    if slide.get("pills"):
        y += 12
        y = block_pills(img, draw, fonts, p, PAD, y,
                        slide["pills"], slide.get("pills_active"))

    layout = slide.get("image_layout", "inline")
    if slide.get("image"):
        ip = cdir / "reference" / slide["image"]
        if not ip.exists():
            ip = Path(slide["image"])
        if ip.exists():
            remaining = C_BOT - y - 24
            if layout == "hero":
                block_hero_image(img, draw, p, ip, PAD, y + 8, C_W,
                                 max_h=max(300, min(520, remaining)))
            else:
                block_image(img, draw, p, ip, PAD, y + 8, C_W,
                            max_h=max(180, min(380, remaining)))

    if slide.get("images") and slide.get("image_layout") == "logo_row":
        paths = [cdir / "reference" / i for i in slide["images"]]
        paths = [p_ for p_ in paths if p_.exists()]
        if paths:
            y = block_logo_row(img, draw, p, paths, PAD, y + 12, C_W)

    if slide.get("images") and slide.get("image_layout") == "split":
        paths = [cdir / "reference" / i for i in slide["images"]]
        if all(p_.exists() for p_ in paths[:2]):
            block_split_images(img, draw, p, paths[0], paths[1],
                               PAD, y + 12, C_W, max_h=380,
                               labels=slide.get("image_labels"))

    return img

def render_cta(config, slide, fonts, theme, cdir):
    """CTA slide — always uses dark theme."""
    p    = theme["themes"]["dark"]
    img  = Image.new("RGB", (W, H), rgb(p["bg"]))
    # Corner glow uses cta_glow_color from theme
    glow = Image.new("RGBA", (W, H), (0, 0, 0, 0))
    gr, gg, gb = rgb(theme["cta_glow_color"])
    ImageDraw.Draw(glow).ellipse([W - 500, -260, W + 260, 520],
                                  fill=(gr, gg, gb, 20))
    glow = glow.filter(ImageFilter.GaussianBlur(180))
    img  = Image.alpha_composite(img.convert("RGBA"), glow).convert("RGB")
    draw = ImageDraw.Draw(img)

    lang    = config.get("language", "en")
    n, t    = slide["number"], config["total_slides"]
    brand   = config["profile"]["display_name"].upper()
    counter = f"{n:02d} / {t:02d}"
    draw.text((PAD, 26), brand, font=fonts["topbar"], fill=rgb(p["label"]))
    cw = draw.textbbox((0, 0), counter, font=fonts["counter"])[2]
    draw.text((W - PAD - cw, 26), counter,
              font=fonts["counter"], fill=rgb(p["muted"]))
    _hairline(draw, p, PAD, TOP_H + 4, W - PAD)
    _hairline(draw, p, PAD, H - BOT_H - 4, W - PAD)
    footer = i18n(theme, lang, "follow_footer", "FOLLOW FOR MORE")
    draw.text((PAD, H - BOT_H + 26), footer,
              font=fonts["caption"], fill=rgb(p["muted"]))

    cx = W // 2
    y  = int(H * 0.15)

    name  = config["profile"]["display_name"]
    nfont = fonts["headline_md"]
    nw    = draw.textbbox((0, 0), name, font=nfont)[2]
    draw.text((cx - nw // 2, y), name, font=nfont, fill=rgb(p["headline"]))
    y += draw.textbbox((0, 0), name, font=nfont)[3] + 20

    handle = config["profile"]["handle"]
    hw = draw.textbbox((0, 0), handle, font=fonts["body"])[2]
    draw.text((cx - hw // 2, y), handle, font=fonts["body"], fill=rgb(p["label"]))
    y += 70

    draw.rounded_rectangle([(cx - 48, y), (cx + 48, y + 5)],
                           radius=2, fill=rgb(p["divider"]))
    y += 44

    cta = slide.get("text", "Follow for more")
    cta_h = th(cta, fonts["body_lg"], C_W - 40, draw, 1.45)
    draw_plain(draw, cta, (PAD + 20, y), fonts["body_lg"],
               p["body"], C_W - 40, sp=1.45, align="center")
    y += cta_h + 48

    if slide.get("button_text"):
        btn   = slide["button_text"]
        bfont = fonts["body_bold"]
        btw   = draw.textbbox((0, 0), btn, font=bfont)[2]
        bw, bh = btw + 88, 72
        bx    = cx - bw // 2

        # Gradient from theme.cta_button_gradient
        grad_colors = theme["cta_button_gradient"]
        grad = Image.new("RGBA", (bw, bh), (0, 0, 0, 0))
        lc, rc = rgb(grad_colors[0]), rgb(grad_colors[1])
        for px_ in range(bw):
            t_ = px_ / bw
            col = tuple(int(lc[i] + (rc[i] - lc[i]) * t_) for i in range(3))
            ImageDraw.Draw(grad).line([(px_, 0), (px_, bh)], fill=col + (255,))
        mask = Image.new("L", (bw, bh), 0)
        ImageDraw.Draw(mask).rounded_rectangle([(0, 0), (bw, bh)],
                                                radius=bh // 2, fill=255)
        pill = Image.new("RGBA", (bw, bh), (0, 0, 0, 0))
        pill.paste(grad, (0, 0), mask)

        glow2 = Image.new("RGBA", (bw + 44, bh + 44), (0, 0, 0, 0))
        glow2.paste(pill, (22, 22), pill)
        glow2 = glow2.filter(ImageFilter.GaussianBlur(14))
        img.paste(glow2, (bx - 22, y - 22), glow2)
        img.paste(pill, (bx, y), pill)
        draw = ImageDraw.Draw(img)

        # Button text uses dark-theme bg color (so it pops on accent gradient)
        bbt = draw.textbbox((0, 0), btn, font=bfont)
        draw.text((bx + (bw - btw) // 2, y + (bh - (bbt[3] - bbt[1])) // 2 - bbt[1]),
                  btn, font=bfont, fill=rgb(p["bg"]))

    return img

# ── Main ──────────────────────────────────────────────────────────────────────
def render(cdir):
    cdir   = Path(cdir)
    config = json.loads((cdir / "config.json").read_text(encoding="utf-8"))
    lang   = config.get("language", "en")
    theme  = load_theme(cdir)
    fonts  = load_fonts(theme, lang)
    slides = config["slides"]
    config["total_slides"] = len(slides)
    print(f"Rendering {len(slides)} slides ({lang})...")
    (cdir / "reference").mkdir(exist_ok=True)

    for i, slide in enumerate(slides):
        slide["number"] = i + 1
        stype = slide.get("type", "body")
        theme_name = slide.get("theme",
                               "dark" if stype in ("hook", "cta") else "light")
        if   stype == "hook": img = render_hook(config, slide, fonts, theme, cdir)
        elif stype == "cta":  img = render_cta(config, slide, fonts, theme, cdir)
        else:                 img = render_body(config, slide, fonts, theme, cdir)
        out = cdir / f"slide_{i+1}.png"
        img.save(str(out), "PNG")
        print(f"  OK slide_{i+1}.png  [{stype:5s}  theme={theme_name}]")

    print(f"\nDone → {cdir}")

if __name__ == "__main__":
    render(sys.argv[1] if len(sys.argv) > 1 else "carousel-test")